---
- name: Deploy and run Pi Dash server
  hosts: pi
  tasks:
    - name: Get virtualenv
      easy_install: name=virtualenv

    - name: Get pip
      easy_install: name=pip

    - name: Stop existing server
      supervisorctl: name=dashboard state=stopped

    - name: Remove deploy directory
      file: path={{ deploy_dir }}/ state=absent

    - name: Create deploy directory
      file: path={{ deploy_dir }}/ state=directory owner=pi group=pi mode=u+rwx

    - name: Get latest version of dashboard
      git: repo=https://github.com/treevesvarndell/dashboard.git dest={{ dashboard_dir }} clone=yes

    - name: Install bower using npm
      npm: name=bower path={{ dashboard_dir }}

    - name: Manually create the initial virtualenv
      command: virtualenv {{ dashboard_dir }}/venv -p python2.7 creates="{{ dashboard_dir }}/venv"

    - name: Install requirements
      pip:
        requirements={{ dashboard_dir }}/requirements.txt
        virtualenv={{ dashboard_dir }}/venv

    - name: Install bower packages
      command: venv/bin/python manage.py bower install chdir={{ dashboard_dir }}

    - name: Copy run script
      copy: src=roles/supervisor/run.sh dest={{ dashboard_dir }}/run.sh owner=pi group=pi mode="u=rwx,g=rx,o=r"

    - name: Restart server using supervisor
      supervisorctl: name=dashboard state=restarted