---
- name: Deploy dashboard
  hosts: pi

  tasks:
    - name: Get pip
      easy_install: name=pip state=latest

    - name: Get virtualenv
      easy_install: name=virtualenv state=latest

    - name: Install bower using npm
      npm: name=bower path=/home/pi/deploy/dashboard/

    - name: Kill existing process on port
      shell: fuser -k -TERM -n tcp 8080
      ignore_errors: yes

    - name: Remove deploy directory
      file: path=/home/pi/deploy/ state=absent

    - name: Create deploy directory
      file: path=/home/pi/deploy/ state=directory owner=pi group=pi mode=u+rwx

    - name: Get latest version of dashboard
      git: repo=https://github.com/treevesvarndell/dashboard.git dest=/home/pi/deploy/dashboard clone=yes

    - name: Manually create the initial virtualenv
      command: virtualenv /home/pi/deploy/dashboard/venv -p python2.7 creates="/home/pi/deploy/dashboard/venv"

    - name: Install requirements
      pip:
        requirements=/home/pi/deploy/dashboard/requirements.txt
        virtualenv=/home/pi/deploy/dashboard/venv

    - name: Install bower packages
      command: venv/bin/python manage.py bower install chdir=/home/pi/deploy/dashboard/

    - name: Run server
      shell: nohup venv/bin/python manage.py runserver 0.0.0.0:8080 chdir=/home/pi/deploy/dashboard/ &